### PR TITLE
adds bson tag to generated structs

### PR DESCRIPTION
**Pull request by HugoJBello**
This pull request adds the tag bson to the struct fhir models. This is important when working with mongodb, otherwise the data is saved only with lower case. This is a problem that we encountered when using golang-fhir-models.

I reopened this pr to squash all commits in one and remove some changes in the previous one.

### CODE REVIEW

**Comment by alexanderkiel** [comment]
Looks very good. You also could have updates your PR by using force push. Can you please remove the .gitignore changes because its one of our policies to not exclude IDE specific files. You can exclude that files with a parent .gitignore on your machine if you like to do so.

**Comment by HugoJBello** [comment]
Ok, done

**Comment by HugoJBello** [comment]
Hi, how do you see this pr? Is there something else I can do?

**Comment by alexanderkiel** [comment]
> Hi, how do you see this pr? Is there something else I can do?

Sorry I had no time to look at it. Thanks for your PR.

**Pull request merged**
